In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("river.csv", header=None)
data

       0     1     2      3
0   4.69  6.59  51.0  11.94
1   2.03  7.86  19.0   6.46
2   9.11  6.31  46.0   8.91
3   8.61  7.05  46.0  26.43
4   7.13  6.50  50.0  23.57
5   2.39  6.77  38.0  24.62
6   7.69  6.79  38.0   6.01
7   9.30  6.81  27.0  31.57
8   5.45  7.62   5.0  18.46
9   6.19  7.27  17.0   7.51
10  7.93  7.53   9.0   6.52
11  4.40  7.28  17.0  25.30
12  7.46  8.24  23.0  14.42
13  2.01  5.55  47.0  26.31
14  2.04  6.40  23.0  17.91
15  7.73  6.14  52.0  15.72
16  6.35  7.58  25.0  29.46
17  8.29  8.41  39.0  12.02
18  3.54  7.27  54.0   3.16
19  7.44  6.26   8.0  28.41

In [3]:
class Topsis:
    def __init__(self,X,**typ):
        # 所有待转换的类型
        x_mat = X.copy()
        ctype = ['cmin','cmedian','crange']
        if typ:
            # 提取待转换类型及对应的列为一个新字典
            type_dic = dict([(t,typ[t]) for t in ctype if t in typ.keys()])
            position = sum(type_dic.values(),[])

            for col_wait_for_convert in position:
                convert_type = [k for k, v in typ.items() if col_wait_for_convert in v][0]
                current_index = typ[convert_type].index(col_wait_for_convert)
                if convert_type == 'cmedian':
                    x_mat.iloc[:,col_wait_for_convert] = self.positivization(x_mat[col_wait_for_convert], convert_type,typ['best_median'][current_index])
                
                elif convert_type == 'crange':
                    x_mat.iloc[:,col_wait_for_convert] = self.positivization(x_mat[col_wait_for_convert], convert_type,typ['best_range'][current_index])
                
                else:
                    x_mat.iloc[:,col_wait_for_convert] = self.positivization(x_mat[col_wait_for_convert],convert_type)
        else:
            print('无需正向化')
            
        self.x_mat = x_mat
            
    def positivization(self, col ,t, best=None):
        if t == 'cmin':
            posit = col.max() - col
            return posit
        elif t == 'cmedian':
            m = max(abs(col - best))
            posit = 1 - abs(col - best) / m
            return posit
        else:
            posit = col
            t == 'crange'
            a,b = best
            m = max(np.append(a-min(col),max(col)-b))
            x_row = col.shape[0]
            for i in range(x_row):
                if col[i] < a:
                    posit[i] = 1 - (a-col[i]) / m
                elif col[i] > b:
                    posit[i] = 1 - (col[i]-b) / m
                else:
                    posit[i] = 1
            return posit
        
    # 计算距离及得分
    def score(self,weight=1):
        Z = self.standardize()
        col_max = Z.max()
        col_min = Z.min()
        D_max_sum = np.sqrt(np.sum(weight*(col_max-Z)**2,axis=1))
        D_min_sum = np.sqrt(np.sum(weight*(col_min-Z)**2,axis=1))
        S = D_min_sum/(D_max_sum+D_min_sum)
        stand_S = S/sum(S)
        self.stand_S = stand_S
        
    # 标准化函数
    def standardize(self):
        # 每列元素平方和
        square_sum = np.square(self.x_mat).sum(axis=0)
        self.standard_mat = self.x_mat / np.sqrt(square_sum)
        
        return self.standard_mat

In [4]:
tp = Topsis(X=data,cmin=[2],cmedian=[1],best_median=[7],crange=[3],best_range=[[10,20]])

In [5]:
tp.score()

In [6]:
tp.stand_S.sort_values(ascending=False)

10    0.070162
9     0.068393
8     0.068074
11    0.059093
19    0.056466
6     0.053947
14    0.053307
12    0.052652
7     0.050998
3     0.048820
2     0.048497
1     0.047799
16    0.046574
0     0.045058
5     0.044838
17    0.043844
15    0.043359
4     0.043113
18    0.035810
13    0.019196
dtype: float64

### 熵权法赋权

In [73]:
def judge(x):
    if x == 0:
        return 0.000001
    else:
        return x

In [80]:
x_mat = tp.x_mat
if (x_mat < 0).astype(np.int).sum().sum() > 0:
    x_mat = (x_mat - x_mat.min()) / (x_mat.max() - x_mat.min())
for i in range(x_mat.shape[1]):
    x_mat.iloc[:,i] = x_mat.iloc[:,i].apply(judge)
x_p = x_mat / x_mat.sum()
info_tropy = -(1/np.log(x_mat.shape[0])) * np.sum(x_p * np.log(x_p))
w = 1 - info_tropy
w = w / sum(w)
print(w)

0    0.141061
1    0.226674
2    0.440935
3    0.191330
dtype: float64